/**
 * Default system prompt and seed knowledge base for the AI chatbot.
 */

export interface KnowledgeEntry {
  id: string;
  title: string;
  content: string;
  category?: string;
}

export const KNOWLEDGE_CATEGORIES = [
  { id: 'pricing', label: 'Pricing & Packages', icon: '💰' },
  { id: 'timing', label: 'Timing & Schedule', icon: '🕐' },
  { id: 'included', label: "What's Included", icon: '✅' },
  { id: 'addons', label: 'Add-Ons', icon: '🎁' },
  { id: 'boats', label: 'Boats & Capacity', icon: '🚤' },
  { id: 'policies', label: 'Policies & FAQs', icon: '📋' },
  { id: 'general', label: 'General', icon: '📌' },
];

export const DEFAULT_SYSTEM_PROMPT = [
  "You are the Premier Party Cruises AI assistant. You help customers plan boat party cruises on Lake Austin in Austin, TX.",
  "",
  "═══════════════════════════════════════════",
  "RULE #1 — ANSWER FIRST, ALWAYS.",
  "═══════════════════════════════════════════",
  "When a customer asks ANY question, ALWAYS give the answer IMMEDIATELY using your knowledge base.",
  "NEVER respond with only a follow-up question. Provide all the info you have, THEN ask for missing details.",
  "Example: 'How much is it?' → Give the full pricing breakdown for ALL options right away, THEN ask guest count/date to calculate a specific total.",
  "Example: 'What times are available?' → Give the full schedule for each day of the week, THEN ask what date they're looking at.",
  "",
  "═══════════════════════════════════════════",
  "RULE #2 — IDEAL CONVERSATION FLOW",
  "═══════════════════════════════════════════",
  "Follow this order when guiding a customer toward a quote. You don't have to force it — let the conversation flow naturally, but aim for this sequence:",
  "",
  "STEP 1: Answer their question fully.",
  "STEP 2: Ask what TYPE OF PARTY they're having. Present these exact options as buttons: Bachelorette Party, Bachelor Party, Combined Bachelorette & Bachelor Party, Wedding Event, Corporate Event, Birthday Party, Graduation Party, Any Other Occasion. Use the suggest_quick_replies tool with 'ask' action for these.",
  "STEP 3: Ask for their EVENT DATE using the show_date_picker tool (if not yet known).",
  "STEP 4: Ask for their GUEST COUNT using the show_guest_selector tool (if not yet known).",
  "STEP 5: Once you know the guest count, tell them which boat fits their group and OFFER TO SHOW PHOTOS by calling the show_boat_photo tool.",
  "STEP 6: If they say BACHELOR, BACHELORETTE, or COMBINED BACH, AND their date is March-October on a Fri/Sat — show them the DISCO CRUISE option with per-person pricing ($85/$95/$105) alongside the private cruise option. Compare both so they can see which is better for their group size. Call show_boat_photo with boat_key 'clever-girl' to show the disco cruise boat.",
  "STEP 7: Show availability for their date/day including all typical time slots. Say 'View full availability calendar' after showing slots.",
  "STEP 8: THEN ask for their contact info to create a personalized quote. Before asking, tell them these 5 reasons to request a quote:",
  "  1. 💰 $150 OFF if you book within 10 days of requesting",
  "  2. 🚐 Discount on round-trip group transportation",
  "  3. 🍹 Free drink delivery & ice delivery to the boat",
  "  4. 📋 Detailed pricing breakdown with all options",
  "  5. 📅 Real-time availability calendar with open time slots",
  "",
  "After listing those reasons, suggest they click 'Get a Quote' in the quick replies.",
  "",
  "═══════════════════════════════════════════",
  "INTERACTIVE WIDGETS",
  "═══════════════════════════════════════════",
  "- show_date_picker: displays an inline calendar. Use when you need a date.",
  "- show_guest_selector: displays a +/- stepper with quick-select bubbles. Use when you need a guest count.",
  "- show_boat_photo: displays a photo of a specific boat. Use after determining the guest count to show the recommended boat. Valid boat_key values: 'day-tripper', 'meeseeks', 'clever-girl'.",
  "- suggest_quick_replies: provide 2-4 clickable buttons after every response.",
  "- You can call MULTIPLE tools in a single response.",
  "",
  "═══════════════════════════════════════════",
  "PRICING RULES (MUST KNOW)",
  "═══════════════════════════════════════════",
  "- Private cruises = FLAT RATE per reservation (hourly × hours). NOT per person.",
  "- Disco cruises = PER PERSON pricing (varies by slot: $95 Fri, $105 Sat AM, $85 Sat PM). No package tiers.",
  "- Sparkle packages and Mimosa Cooler are optional ADD-ONS (flat fee per group), not ticket tiers.",
  "- Disco cruises are ALWAYS 4 hours, no shorter option.",
  "- Additional fees on top of base price: 20% gratuity, 8.25% tax, 3% booking fee.",
  "- $150 discount if they book within 10 days of requesting a quote.",
  "- Extra crew fees: +$50/hr for 26-30 guests, +$100/hr for 51-75 guests.",
  "",
  "FLEET:",
  "- Day Tripper: up to 14 guests",
  "- Meeseeks / The Irony: up to 25 guests (30 with extra crew)",
  "- Clever Girl: up to 50 guests (75 with extra crew), also hosts disco cruises (max 100 tickets)",
  "",
  "DISCO CRUISE SCHEDULE (March-October only, bach parties only):",
  "- Friday: 12-4 PM ($95/pp) | Saturday: 11 AM-3 PM ($105/pp) and 3:30-7:30 PM ($85/pp)",
  "",
  "PRIVATE CRUISE TIME SLOTS:",
  "- Mon-Thu: Various times available (3hr and 4hr options)",
  "- Friday: 12-4 PM or 4:30-8:30 PM (4hr)",
  "- Saturday: 11 AM-3 PM or 3:30-7:30 PM (4hr)",
  "- Sunday: 11 AM-3 PM or 3:30-7:30 PM (4hr)",
  "",
  "IMPORTANT CONTEXT:",
  "- Premier Party Cruises operates year-round for private cruises",
  "- ATX Disco Cruises run March through October (Friday & Saturday only)",
  "- All cruises are on Lake Austin, Texas",
  "- BYOB (Bring Your Own Beverages) on all cruises — no glass allowed",
  "- We handle everything: captain, crew, fuel, life jackets included",
  "- Booking is at booking.premierpartycruises.com",
].join("\n");

export const SEED_KNOWLEDGE: KnowledgeEntry[] = [
  // PRICING & PACKAGES
  {
    id: 'pricing-private-hourly',
    title: 'Private Cruise Hourly Rates',
    content: [
      "Private cruise pricing varies by day of week and guest count tier. These are PER RESERVATION (flat rate), NOT per person.",
      "",
      "**1-14 Guests (Day Tripper boat):**",
      "- Mon-Thu: $200/hr | Friday: $250/hr | Saturday: $350/hr | Sunday: $250/hr",
      "",
      "**15-25 Guests (Meeseeks or The Irony):**",
      "- Mon-Thu: $225/hr | Friday: $300/hr | Saturday: $375/hr | Sunday: $275/hr",
      "",
      "**26-30 Guests (Meeseeks or The Irony + extra crew):**",
      "- Same base rates as 15-25 tier PLUS $50/hr crew fee",
      "",
      "**31-50 Guests (Clever Girl):**",
      "- Mon-Thu: $250/hr | Friday: $300/hr | Saturday: $400/hr | Sunday: $275/hr",
      "",
      "**51-75 Guests (Clever Girl + extra crew):**",
      "- Same base rates as 31-50 tier PLUS $100/hr crew fee",
      "",
      "Standard booking is 4 hours. 3-hour cruises are available on some time slots (typically weekday or off-peak times).",
      "",
      "All pricing includes: 20% gratuity, 8.25% tax, and 3% booking fee calculated on top.",
      "",
      "EXAMPLE 4-hour totals (Base package, no add-ons):",
      "- 14p Saturday: ~$1,838 | 14p Friday: ~$1,313 | 14p Weekday: ~$1,050",
      "- 25p Saturday: ~$1,969 | 25p Friday: ~$1,575 | 25p Weekday: ~$1,181",
      "- 50p Saturday: ~$2,100 | 50p Friday: ~$1,575 | 50p Weekday: ~$1,313",
    ].join("\n"),
    category: 'pricing',
  },
  {
    id: 'pricing-packages',
    title: 'Private Cruise Package Tiers & Add-Ons',
    content: [
      "All private cruises offer three package tiers:",
      "",
      "**Base Package** - No additional cost. Includes boat rental with captain, crew, fuel, BYOB, and life jackets.",
      "",
      "**Essentials Package** - Ready When You Arrive!",
      "- 14-person boat (Day Tripper): +$100",
      "  • 3 Bubble Wands, 6-Foot Folding Table, (2) Large Coolers, 40lbs of Ice, 5-Gallon Water Dispenser, 10 Gallons of Water, 25 Solo Cups",
      "",
      "- 25-person boat (Meeseeks/Irony): +$150",
      "  • 3 Bubble Wands, 6-Foot Folding Table, (3) Large Coolers, 60lbs of Ice, 5-Gallon Water Dispenser, 15 Gallons of Water, 50 Solo Cups",
      "",
      "- 50-person boat (Clever Girl): +$200",
      "  • 3 Bubble Wands, (2) 6-Foot Folding Tables, (3) 5-ft Coolers, 80lbs of Ice, 5-Gallon Water Dispenser, 15 Gallons of Water, 75 Solo Cups",
      "",
      "**Ultimate Party Package** - Everything Ready When You Arrive!",
      "- 14-person boat: +$250",
      "  • Personal Unicorn Float, (3) Disco Balls Installed, Bubble Gun, 3 Bubble Wands, 6'x20' Lily Pad Float, 3 Disco Ball Cups, 20 Champagne Flutes, 3 Fruit Juices, 2 Coolers, 40 lbs of Ice, 15 Gallons of Water, 5-Gallon Water Dispenser, 30 Solo Cups, 2 Bottles of SPF-50 Spray Sunscreen",
      "",
      "- 25-person boat: +$300",
      "  • (2) Personal Unicorn Floats, (3) Disco Balls Installed, Bubble Gun, (3) Bubble Wands, (2) 6'x20' Lily Pad Floats, (5) Disco Ball Cups, 30 Champagne Flutes, 3 Fruit Juices, 3 Coolers, 60lbs of Ice, 15 Gallons of Water, 5-Gallon Water Dispenser, 50 Solo Cups, 2 Bottles of SPF-50 Spray Sunscreen",
      "",
      "- 50-person boat: +$350",
      "  • (3) Personal Unicorn Floats, (2) Bubble Guns, (3) 6'x20' Lily Pad Floats, (5) Disco Ball Cups, 50 Champagne Flutes, 3 Fruit Juices, 3 Giant Coolers, 80 lbs of Ice, 15 Gallons of Water, 5-Gallon Water Dispenser, 75 Solo Cups, 4 Bottles of SPF-50 Spray Sunscreen",
      "",
      "**Additional Private Cruise À La Carte Add-Ons:**",
      "- Professional DJ: $600",
      "- Professional Photographer: $600",
      "- Bartender: $600",
      "- A/V Setup (wireless mic & projector screen): $300",
      "- Party Cooler Setup: $150",
      "- Lily Pad Float: $50 each",
      "- Personal Unicorn Float: $20 each",
      "- 5 Premier Koozies: $20",
      "- 20-lb Bag of Ice: $8 each",
      "- Bubble Wands: $3 each",
      "- Mimosa Cooler (private cruise version): $100",
    ].join("\n"),
    category: 'pricing',
  },
  {
    id: 'pricing-disco-cruises',
    title: 'ATX Disco Cruise Pricing & Add-Ons',
    content: [
      "ATX Disco Cruises are PER-PERSON ticketed events for bach parties only (March-October, Fri & Sat).",
      "Maximum 100 tickets per cruise. The boat is Clever Girl (50-person base capacity).",
      "",
      "**Single ticket price varies by time slot:**",
      "- Friday 12:00-4:00 PM: **$95/person**",
      "- Saturday 11:00 AM-3:00 PM: **$105/person**",
      "- Saturday 3:30-7:30 PM: **$85/person**",
      "",
      "Every ticket includes: admission, giant unicorn float, souvenir koozies, DJ, photographer, lily pad floats, cooler with ice, private storage, party favors.",
      "",
      "**Disco Cruise Optional Add-Ons (flat fee per group, NOT per person):**",
      "",
      "1. **Mimosa Party Cooler — $100** (available for all bach types)",
      "   • Large extra cooler with ice",
      "   • 3 fruit juices",
      "   • Champagne flutes (1 per person)",
      "   • A Chambong",
      "   • 3 bubble wands",
      "",
      "2. **Bride Sparkle Package — $100** (bachelorette parties only)",
      "   • Disco ball cup for the bride",
      "   • Bubble gun",
      "   • Disco bopper headband",
      "   • Personal unicorn float for the bride",
      "   • SPF-50 sunscreen spray (1 bottle per 5 people)",
      "   • Disco ball necklaces for the whole group",
      "",
      "3. **Groom Manly Sparkle Package — $100** (bachelor parties only)",
      "   • Disco ball cup for the groom",
      "   • Disco ball necklaces for the crew",
      "   • 'Bad Day to Be a Beer' flag",
      "   • SPF-50 sunscreen spray",
      "   • Personal unicorn float for the groom",
      "",
      "4. **Sparkle Together Package — $150** (combined bach parties only)",
      "   • Disco ball cups for both bride AND groom",
      "   • Disco ball necklaces for the crew",
      "   • 'Bad Day to Be a Beer' flag",
      "   • SPF-50 sunscreen spray",
      "   • Personal unicorn floats for both bride AND groom",
      "   • 2 bubble guns",
      "   • Disco bopper headband for the bride",
      "",
      "5. **5 Disco Ball Cups — $30**",
      "   • Set of 5 reusable disco ball cups for your group",
      "   • Also available as 10 disco ball cups for $60",
      "",
      "IMPORTANT: Sparkle packages are group-type-specific! Only show the relevant one:",
      "- Bachelorette → Bride Sparkle Package",
      "- Bachelor → Groom Manly Sparkle Package", 
      "- Combined Bach → Sparkle Together Package",
      "",
      "EXAMPLE: 15 people on a Friday = 15 × $95 = $1,425 (plus taxes/fees)",
      "Disco cruises are only for Bach party types and are always 4 hours long — no 3-hour option.",
    ].join("\n"),
    category: 'pricing',
  },
  {
    id: 'pricing-crew-fees',
    title: 'Extra Crew Fees for Large Groups',
    content: [
      "When groups exceed the base boat capacity, additional crew fees apply:",
      "",
      "**26-30 guests** on a 25-person boat (Meeseeks/Irony): +$50/hr crew fee",
      "Example: 28 guests on a Friday 4-hour cruise = base $300/hr × 4 + crew $50/hr × 4 = $1,200 + $200 = $1,400 subtotal",
      "",
      "**51-75 guests** on a 50-person boat (Clever Girl): +$100/hr crew fee",
      "Example: 60 guests on a Saturday 4-hour cruise = base $400/hr × 4 + crew $100/hr × 4 = $1,600 + $400 = $2,000 subtotal",
      "",
      "These are added as separate line items. Gratuity, tax, and booking fee are calculated on the total including crew fees.",
    ].join("\n"),
    category: 'pricing',
  },
  {
    id: 'pricing-duration-options',
    title: 'Cruise Duration Options (3-Hour vs 4-Hour)',
    content: [
      "**Private Cruises:**",
      "- Standard booking is 4 hours",
      "- 3-hour cruises may be available on some time slots, typically weekday or off-peak times",
      "- Duration depends on available time slots in the calendar",
      "- Minimum booking is typically 3 hours",
      "- Longer durations (5-6 hours) can be arranged by contacting us",
      "",
      "**Disco Cruises:**",
      "- ALL disco cruises are exactly 4 hours — no shorter option",
      "- Friday: 12:00 PM - 4:00 PM",
      "- Saturday Slot 1: 11:00 AM - 3:00 PM",
      "- Saturday Slot 2: 3:30 PM - 7:30 PM",
      "",
      "To calculate 3-hour pricing, simply multiply the hourly rate by 3 instead of 4.",
      "Example: 14p weekday 3-hour = $200/hr × 3 = $600 base (+ tax, gratuity, fees = ~$788)",
    ].join("\n"),
    category: 'pricing',
  },
  {
    id: 'pricing-total-breakdown',
    title: 'How the Total Price is Calculated',
    content: [
      "Here's exactly how we calculate your total:",
      "",
      "1. **Subtotal** = (Hourly Rate × Hours) + Crew Fee (if applicable) + Package Add-on (if any)",
      "2. **Discount** = If promo code or $150 booking discount applies, subtract from subtotal",
      "3. **Gratuity** = 20% of discounted subtotal",
      "4. **Booking Fee** = 3% of (discounted subtotal + gratuity)",
      "5. **Sales Tax** = 8.25% of original subtotal (before discount)",
      "6. **TOTAL** = Discounted Subtotal + Gratuity + Booking Fee + Sales Tax",
      "",
      "The $150 discount is available when you book within 10 days of requesting a quote.",
    ].join("\n"),
    category: 'pricing',
  },
  {
    id: 'pricing-disco-vs-private',
    title: 'Disco Cruise vs Private Cruise — When to Choose Which',
    content: [
      "**Choose a Disco Cruise if:**",
      "- You're a bach party (bachelorette, bachelor, or combined)",
      "- Your date is March-October on a Friday or Saturday",
      "- You want a per-person price (no flat rate commitment)",
      "- You want DJ, photographer, and party supplies included",
      "- You have 6-100 people",
      "",
      "**Choose a Private Cruise if:**",
      "- You want the whole boat to yourself",
      "- You're any party type (birthday, company, family, etc.)",
      "- You want flexibility on date/time (any day, year-round)",
      "- You have 1-75 people",
      "- You want to customize your experience (bring your own DJ, etc.)",
      "",
      "**Cost comparison example (20 people, Saturday 3:30 PM slot):**",
      "- Disco Cruise: 20 × $85 = $1,700 + fees",
      "- Private 25p Base: $375/hr × 4 = $1,500 + fees ≈ $1,969",
      "- Private cruise is often cheaper for larger groups AND you get the whole boat!",
    ].join("\n"),
    category: 'pricing',
  },

  // TIMING & SCHEDULE
  {
    id: 'timing-private',
    title: 'Private Cruise Availability & Time Slots',
    content: [
      "Private cruises are available year-round, 7 days a week on Lake Austin.",
      "",
      "Typical booking durations: 3-6 hours. Standard is 4 hours.",
      "",
      "**Typical Private Cruise Time Slots by Day of Week:**",
      "",
      "**Monday–Thursday (Weekdays):**",
      "- 9:00 AM – 12:00 PM (3 hours) — available on some boats",
      "- 9:00 AM – 1:00 PM (4 hours)",
      "- 12:00 PM – 4:00 PM (4 hours)",
      "- 1:00 PM – 4:00 PM (3 hours) — available on some boats",
      "- 4:00 PM – 8:00 PM (4 hours, sunset)",
      "- 3-hour cruises are ONLY available on weekdays, not weekends",
      "",
      "**Friday:**",
      "- 12:00 PM – 4:00 PM (4 hours)",
      "- 4:30 PM – 8:30 PM (4 hours, sunset)",
      "- No 3-hour options on Fridays",
      "",
      "**Saturday:**",
      "- 11:00 AM – 3:00 PM (4 hours)",
      "- 3:30 PM – 7:30 PM (4 hours)",
      "- Most popular day — book early! No 3-hour options.",
      "",
      "**Sunday:**",
      "- 11:00 AM – 3:00 PM (4 hours)",
      "- 3:30 PM – 7:30 PM (4 hours)",
      "- No 3-hour options on Sundays",
      "",
      "When selecting a weekday date, the quote builder also shows that upcoming weekend's availability.",
      "When selecting a weekend date, it shows Friday, Saturday, and Sunday options.",
      "",
      "IMPORTANT: Actual availability depends on what's already booked. The quote builder shows real-time availability. Always encourage users to 'View the full availability calendar' to see exactly what's open.",
    ].join("\n"),
    category: 'timing',
  },
  {
    id: 'timing-disco',
    title: 'ATX Disco Cruise Schedule',
    content: [
      "ATX Disco Cruises operate March 1 through October 31 only.",
      "All disco cruises are 4 hours. No 3-hour option.",
      "",
      "**Friday Schedule:**",
      "- 12:00 PM – 4:00 PM (1 slot per Friday)",
      "",
      "**Saturday Schedule:**",
      "- 11:00 AM – 3:00 PM (Slot 1)",
      "- 3:30 PM – 7:30 PM (Slot 2)",
      "",
      "**Sunday–Thursday:** No disco cruises available.",
      "",
      "All disco cruises are on the Clever Girl boat.",
      "Maximum 100 tickets per cruise.",
      "Only available for Bach party types (Bachelorette, Bachelor, Combined Bach).",
      "Non-bach party types (birthday, company, family, etc.) cannot book disco cruises — they should book a private cruise instead.",
    ].join("\n"),
    category: 'timing',
  },
  {
    id: 'timing-season',
    title: 'Seasonal Information',
    content: [
      "**Peak Season:** March – October (spring/summer). Saturday is the most expensive day.",
      "**Off Season:** November – February. Private cruises still available at regular rates.",
      "**Disco Cruise Season:** March 1 – October 31 only (Fridays & Saturdays).",
      "",
      "Weather: Austin is generally warm March-October. Boats have shade coverings. All cruises are weather-dependent — we will reschedule if conditions are unsafe.",
    ].join("\n"),
    category: 'timing',
  },
  {
    id: 'timing-availability-guidance',
    title: 'How to Guide Users to Check Availability',
    content: [
      "When a user asks about availability for a specific date:",
      "1. Ask what day of the week their date falls on (or determine it from the date)",
      "2. Tell them the typical time slots available for that day",
      "3. If it's a bach party on Fri/Sat in March-October, mention disco cruise options too",
      "4. Based on their guest count, tell them which boat they'd be on",
      "5. Always end with: 'To see real-time availability and exact open time slots, view the full availability calendar in the quote builder!'",
      "6. Suggest they request a quote to lock in their date — spots fill fast on weekends!",
      "",
      "**Boat assignment by guest count:**",
      "- 1-14 guests → Day Tripper",
      "- 15-25 guests → Meeseeks or The Irony",
      "- 26-30 guests → Meeseeks or The Irony + extra crew",
      "- 31-50 guests → Clever Girl",
      "- 51-75 guests → Clever Girl + extra crew",
    ].join("\n"),
    category: 'timing',
  },

  // WHAT'S INCLUDED
  {
    id: 'included-all-cruises',
    title: 'What Every Private Cruise Includes',
    content: [
      "Every Premier Party Cruise includes at no extra charge:",
      "- Professional captain and crew",
      "- All fuel costs",
      "- Life jackets for all guests",
      "- BYOB (Bring Your Own Beverages - no glass allowed)",
      "- Bluetooth/premium sound system",
      "- Coolers with ice (base amount)",
      "- Shade covering/canopy",
      "",
      "We cruise on beautiful Lake Austin with scenic views, swimming stops, and more!",
    ].join("\n"),
    category: 'included',
  },
  {
    id: 'included-disco-ticket',
    title: 'What Every Disco Cruise Ticket Includes',
    content: [
      "Every ATX Disco Cruise ticket includes:",
      "- Admission to the 4-hour cruise",
      "- Giant unicorn float",
      "- Souvenir koozies",
      "- Professional DJ",
      "- Professional photographer",
      "- Lily pad floats",
      "- Cooler with ice",
      "- Private storage for your group",
      "- Party favors",
      "",
      "Ticket prices vary by time slot: $95 (Fri), $105 (Sat AM), $85 (Sat PM).",
      "",
      "Optional add-ons (flat fee per group):",
      "- Mimosa Party Cooler: $100",
      "- Bride Sparkle Package: $100 (bachelorette)",
      "- Groom Manly Sparkle Package: $100 (bachelor)",
      "- Sparkle Together Package: $150 (combined bach)",
    ].join("\n"),
    category: 'included',
  },

  // ADD-ONS
  {
    id: 'addons-disco',
    title: 'Disco Cruise Add-Ons',
    content: [
      "Available add-ons for ATX Disco Cruises (group-type specific):",
      "",
      "**Mimosa Party Cooler - $100** (all bach types)",
      "Extra cooler with ice, 3 fruit juices, champagne flutes (1 per person), a Chambong, 3 bubble wands.",
      "",
      "**Bride Sparkle Package - $100** (Bachelorette only)",
      "Disco ball cup for bride, bubble gun, disco bopper headband, personal unicorn float, SPF-50 sunscreen, disco ball necklaces for whole group.",
      "",
      "**Groom Manly Sparkle Package - $100** (Bachelor only)",
      "Disco ball cup for groom, disco ball necklaces for crew, 'Bad Day to Be a Beer' flag, SPF-50 sunscreen, personal unicorn float.",
      "",
      "**Sparkle Together Package - $150** (Combined Bach only)",
      "Disco ball cups for both bride & groom, necklaces, flag, sunscreen, 2 unicorn floats, 2 bubble guns, disco bopper headband.",
    ].join("\n"),
    category: 'addons',
  },
  {
    id: 'addons-private',
    title: 'Private Cruise Add-Ons & Services',
    content: [
      "Available add-ons for private cruises:",
      "- Essentials Package: $100-$200 (varies by boat size)",
      "- Ultimate Package: $250-$350 (varies by boat size)",
      "- Professional DJ",
      "- Photographer",
      "- Bartender service",
      "- A/V Setup (speakers, microphone)",
      "",
      "Package pricing by boat:",
      "- Day Tripper (14p): Essentials $100, Ultimate $250",
      "- Meeseeks/Irony (25p): Essentials $150, Ultimate $300",
      "- Clever Girl (50p): Essentials $200, Ultimate $350",
    ].join("\n"),
    category: 'addons',
  },
  {
    id: 'addons-pod',
    title: 'Party On Delivery (POD) Vouchers',
    content: [
      "**$50 POD Voucher:**",
      "- Free Direct-to-Boat Alcohol Delivery ($25)",
      "- Free Stock-the-Cooler Service",
      "- Reserved Spot for Your Group",
      "- Mystery Gift for Guest of Honor!",
      "",
      "**$100 POD Concierge Voucher:**",
      "- Free Airbnb/Hotel Alcohol Delivery ($25)",
      "- Free Stock-the-Fridge Service ($25)",
      "- Free Austin Survival Package ($60) — Includes: 12pk Rambler Sparkling Water, Chips & Salsa, 8 Shot Glasses, 4 Fresh Limes, 20 Solo Cups, 10 Ping Pong Balls, 20lbs of Ice, & 10 Electrolyte Recovery Packets",
    ].join("\n"),
    category: 'addons',
  },

  // BOATS & CAPACITY
  {
    id: 'boats-fleet',
    title: 'Our Fleet — All Boats & Capacities',
    content: [
      "**Day Tripper** — Up to 14 guests",
      "Small and nimble, perfect for intimate groups. Bluetooth sound, coolers with ice, shade covering. Ideal for small bach parties, couples, families, or friend groups.",
      "",
      "**Meeseeks** — Up to 25 guests (30 with extra crew at +$50/hr)",
      "Spacious upper deck with luxury lounge seating, premium sound system, shade covering. One of our twin 30-passenger boats.",
      "",
      "**The Irony** — Up to 25 guests (30 with extra crew at +$50/hr)",
      "Classic double-decker with wooden deck and red accents. Comfortable bench seating, great sound. Twin to Meeseeks — whichever is available gets assigned.",
      "",
      "**Clever Girl** — Up to 50 guests (75 with extra crew at +$100/hr)",
      "Our largest boat. Used for ATX Disco Cruises AND large private events. Spacious layout, premium amenities, covered seating.",
      "",
      "All boats are on Lake Austin, TX. All include captain, crew, fuel, BYOB, life jackets.",
    ].join("\n"),
    category: 'boats',
  },
  {
    id: 'boats-capacity-tiers',
    title: 'Guest Count → Boat Assignment Rules',
    content: [
      "Guest count determines which boat and pricing tier automatically:",
      "",
      "- **1-14 guests** → Day Tripper (14-person boat)",
      "- **15-25 guests** → Meeseeks or The Irony (interchangeable 25-person boats)",
      "- **26-30 guests** → Meeseeks or The Irony + extra crew ($50/hr added)",
      "- **31-50 guests** → Clever Girl (50-person boat)",
      "- **51-75 guests** → Clever Girl + extra crew ($100/hr added)",
      "",
      "For disco cruises: all use Clever Girl regardless of group size. Max 100 tickets per disco cruise.",
      "",
      "You can always request a larger boat at the higher tier's rate if you want more space.",
    ].join("\n"),
    category: 'boats',
  },
  {
    id: 'boats-disco-capacity',
    title: 'Disco Cruise Capacity Rules',
    content: [
      "ATX Disco Cruises always operate on the Clever Girl boat.",
      "",
      "- Base capacity: 50 people",
      "- Maximum capacity: 100 tickets per cruise (with extra crew)",
      "- Multiple bach groups can share the same disco cruise time slot",
      "- Each group gets their own reserved section, cooler, and storage",
      "",
      "This is different from private cruises where you rent the entire boat exclusively.",
    ].join("\n"),
    category: 'boats',
  },

  // POLICIES
  {
    id: 'policies-byob',
    title: 'BYOB Policy',
    content: [
      "All Premier Party Cruises are BYOB (Bring Your Own Beverages).",
      "- You bring all your own drinks (beer, wine, spirits, mixers, non-alcoholic)",
      "- NO GLASS containers allowed on any boat - cans and plastic only",
      "- We provide coolers with ice to keep your drinks cold",
      "- Party On Delivery (POD) can deliver alcohol directly to the boat or your Airbnb/hotel for convenience",
    ].join("\n"),
    category: 'policies',
  },
  {
    id: 'policies-booking',
    title: 'Booking & Payment',
    content: [
      "- Deposit required to secure your date (amount varies by package)",
      "- Balance due before cruise date",
      "- Payment plans available for larger bookings",
      "- Book online at booking.premierpartycruises.com or through our quote builder",
      "- Xola booking system used for disco cruise tickets",
      "- Stripe used for private cruise invoicing",
      "- $150 discount available when you book within 10 days of receiving your quote",
    ].join("\n"),
    category: 'policies',
  },
  {
    id: 'policies-discount',
    title: '$150 Booking Discount',
    content: [
      "Every new lead who requests a quote gets a $150 discount if they book within 10 days.",
      "- The countdown timer appears on their personalized quote page",
      "- The discount is subtracted from the base cruise subtotal before gratuity and fees are calculated",
      "- This is the best deal we offer — it's designed to encourage quick booking",
      "- After 10 days, the discount expires and the full price applies",
    ].join("\n"),
    category: 'policies',
  },
  {
    id: 'policies-transport',
    title: 'Transportation Options',
    content: [
      "We partner with transportation providers for round-trip group transport:",
      "",
      "- **Fetii**: 12-14 passenger Sprinter vans",
      "- **Fly Rides / Let's Roll ATX**: 30-passenger party bus (prioritized option)",
      "- Use code 'PPCAUSTIN' for 25% off transportation through our partners",
      "",
      "Transport is optional but highly recommended — the marina is about 25 minutes from downtown Austin.",
    ].join("\n"),
    category: 'policies',
  },
];
